server.error.include-message: always
server.port: 8000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smart_farm}
    username: ${DB_USERNAME:khangvt146}
    password: ${DB_PASSWORD:khang123@@}
    platform: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092} #118.69.53.93:29092

  consumer:
    group-id: ${KAFKA_TS_EVENT_GROUP_ID:smart_farm_event_config}
    auto-offset-reset: ${KAFKA_TS_EVENT_AUTO_OFFSET_RESET:earliest}
    max-concurrency: ${KAFKA_MAX_CONCURRENCY:2}

    temperature:
      topic-in: smart_farm_temperature


  # profile dev
  topics:
    alarm-topic: ${KAFKA_ALARM_TOPIC:alarm}

logging:
  level:
    root: INFO
    com.spm: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


app:
  data_frequency_mins: 30